splunk:
  conf:
    - key: props
      value: 
        directory: /opt/splunk/etc/apps
        content:
          default:
            KV_MODE : auto
  hec:
    enable: True
    ssl: false
    port: 8088
    token: bb3714bf-b59c-4971-94b7-30c9244c803a